import Mathlib.LinearAlgebra.FiniteDimensional.Defs

/-!
# The bordered-matrix lemma

This file formalizes the linear-algebra lemma used in `PROOF.md`, Section 4.
If `H v = 0`, a coordinate functional does not vanish on `v`, and the
bordered operator

```text
    (x, c) |-> (H x + c v, phi x)
```

is injective, then `ker H` is generated by `v` and `v` is not in the range of
`H`. These are the two facts used to rule out additional Jordan vectors at the
certified eigenvalue.
-/

namespace KnuthFasc8aEx210

section BorderLemma

variable {K V : Type*} [Field K] [AddCommGroup V] [Module K V]

/-- The operator represented by the bordered matrix `[H v; phi 0]`. -/
def borderedOperator (H : V →ₗ[K] V) (v : V) (phi : V →ₗ[K] K) :
    V × K → V × K :=
  fun z => (H z.1 + z.2 • v, phi z.1)

/-- Injectivity of the bordered operator forces every vector in `ker H` to be
a scalar multiple of the displayed kernel vector. -/
theorem eq_smul_of_mem_ker_of_bordered_injective
    (H : V →ₗ[K] V) (v : V) (phi : V →ₗ[K] K)
    (Hv : H v = 0) (phi_v : phi v ≠ 0)
    (border_injective : Function.Injective (borderedOperator H v phi))
    {x : V} (Hx : H x = 0) :
    ∃ c : K, x = c • v := by
  let c : K := phi x / phi v
  let y : V := x - c • v
  have Hy : H y = 0 := by
    simp [y, Hx, Hv]
  have phi_y : phi y = 0 := by
    simp [y, c, phi_v]
  have pair_eq : (y, (0 : K)) = (0, 0) := by
    apply border_injective
    simp [borderedOperator, Hy, phi_y]
  refine ⟨c, ?_⟩
  have y_eq_zero : y = 0 := congrArg Prod.fst pair_eq
  exact sub_eq_zero.mp (by simpa [y] using y_eq_zero)

/-- The kernel of `H` is exactly the line generated by `v`. -/
theorem ker_eq_span_of_bordered_injective
    (H : V →ₗ[K] V) (v : V) (phi : V →ₗ[K] K)
    (Hv : H v = 0) (phi_v : phi v ≠ 0)
    (border_injective : Function.Injective (borderedOperator H v phi)) :
    LinearMap.ker H = Submodule.span K {v} := by
  apply le_antisymm
  · intro x hx
    rw [LinearMap.mem_ker] at hx
    obtain ⟨c, rfl⟩ :=
      eq_smul_of_mem_ker_of_bordered_injective H v phi Hv phi_v
        border_injective hx
    exact Submodule.smul_mem _ c
      (Submodule.subset_span (Set.mem_singleton v))
  · apply Submodule.span_le.mpr
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact LinearMap.mem_ker.mpr Hv

/-- The displayed kernel vector is not in the range of `H`; hence there is no
length-two Jordan chain ending in `v`. -/
theorem not_mem_range_of_bordered_injective
    (H : V →ₗ[K] V) (v : V) (phi : V →ₗ[K] K)
    (Hv : H v = 0) (phi_v : phi v ≠ 0)
    (border_injective : Function.Injective (borderedOperator H v phi)) :
    v ∉ LinearMap.range H := by
  intro v_in_range
  obtain ⟨x, Hx⟩ := v_in_range
  let c : K := phi x / phi v
  let y : V := x - c • v
  have Hy : H y = v := by
    simp [y, Hx, Hv]
  have phi_y : phi y = 0 := by
    simp [y, c, phi_v]
  have pair_eq : (y, (-1 : K)) = (0, 0) := by
    apply border_injective
    simp [borderedOperator, Hy, phi_y]
  have absurd : (-1 : K) = 0 := congrArg Prod.snd pair_eq
  exact one_ne_zero (neg_eq_zero.mp absurd)

end BorderLemma

end KnuthFasc8aEx210
