import Mathlib.LinearAlgebra.Eigenspace.Zero
import Mathlib.LinearAlgebra.FiniteDimensional.Basic

/-!
# The bordered-matrix lemma

This file formalizes the linear-algebra lemma used in `PROOF.md`, Section 4.
If `H v = 0`, a coordinate functional does not vanish on `v`, and the
bordered operator

```text
    (x, c) |-> (H x + c v, phi x)
```

is injective, then `ker H` is generated by `v` and `v` is not in the range of
`H`. These are the two facts used to rule out additional Jordan vectors at the
certified eigenvalue.
-/

namespace KnuthFasc8aEx210

section BorderLemma

open Module

variable {K V : Type*} [Field K] [AddCommGroup V] [Module K V]

/-- The operator represented by the bordered matrix `[H v; phi 0]`. -/
def borderedOperator (H : V →ₗ[K] V) (v : V) (phi : V →ₗ[K] K) :
    V × K → V × K :=
  fun z => (H z.1 + z.2 • v, phi z.1)

/-- Injectivity of the bordered operator forces every vector in `ker H` to be
a scalar multiple of the displayed kernel vector. -/
theorem eq_smul_of_mem_ker_of_bordered_injective
    (H : V →ₗ[K] V) (v : V) (phi : V →ₗ[K] K)
    (Hv : H v = 0) (phi_v : phi v ≠ 0)
    (border_injective : Function.Injective (borderedOperator H v phi))
    {x : V} (Hx : H x = 0) :
    ∃ c : K, x = c • v := by
  let c : K := phi x / phi v
  let y : V := x - c • v
  have Hy : H y = 0 := by
    simp [y, Hx, Hv]
  have phi_y : phi y = 0 := by
    simp [y, c, phi_v]
  have pair_eq : (y, (0 : K)) = (0, 0) := by
    apply border_injective
    simp [borderedOperator, Hy, phi_y]
  refine ⟨c, ?_⟩
  have y_eq_zero : y = 0 := congrArg Prod.fst pair_eq
  exact sub_eq_zero.mp (by simpa [y] using y_eq_zero)

/-- The kernel of `H` is exactly the line generated by `v`. -/
theorem ker_eq_span_of_bordered_injective
    (H : V →ₗ[K] V) (v : V) (phi : V →ₗ[K] K)
    (Hv : H v = 0) (phi_v : phi v ≠ 0)
    (border_injective : Function.Injective (borderedOperator H v phi)) :
    LinearMap.ker H = Submodule.span K {v} := by
  apply le_antisymm
  · intro x hx
    rw [LinearMap.mem_ker] at hx
    obtain ⟨c, rfl⟩ :=
      eq_smul_of_mem_ker_of_bordered_injective H v phi Hv phi_v
        border_injective hx
    exact Submodule.smul_mem _ c
      (Submodule.subset_span (Set.mem_singleton v))
  · apply Submodule.span_le.mpr
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact LinearMap.mem_ker.mpr Hv

/-- The displayed kernel vector is not in the range of `H`; hence there is no
length-two Jordan chain ending in `v`. -/
theorem not_mem_range_of_bordered_injective
    (H : V →ₗ[K] V) (v : V) (phi : V →ₗ[K] K)
    (Hv : H v = 0) (phi_v : phi v ≠ 0)
    (border_injective : Function.Injective (borderedOperator H v phi)) :
    v ∉ LinearMap.range H := by
  intro v_in_range
  obtain ⟨x, Hx⟩ := v_in_range
  let c : K := phi x / phi v
  let y : V := x - c • v
  have Hy : H y = v := by
    simp [y, Hx, Hv]
  have phi_y : phi y = 0 := by
    simp [y, c, phi_v]
  have pair_eq : (y, (-1 : K)) = (0, 0) := by
    apply border_injective
    simp [borderedOperator, Hy, phi_y]
  have absurd : (-1 : K) = 0 := congrArg Prod.snd pair_eq
  exact one_ne_zero (neg_eq_zero.mp absurd)

/-- If the kernel is generated by `v` and `v` is not in the range, then the
kernel and range meet trivially. -/
theorem disjoint_ker_range_of_ker_eq_span_of_not_mem_range
    (H : V →ₗ[K] V) (v : V)
    (ker_eq_span : LinearMap.ker H = Submodule.span K {v})
    (v_not_mem_range : v ∉ LinearMap.range H) :
    Disjoint (LinearMap.ker H) (LinearMap.range H) := by
  rw [disjoint_iff_inf_le]
  intro x hx
  have x_mem_span : x ∈ Submodule.span K {v} := ker_eq_span ▸ hx.1
  obtain ⟨c, hcx⟩ := Submodule.mem_span_singleton.mp x_mem_span
  by_cases hc : c = 0
  · simpa [hc] using hcx.symm
  · exfalso
    apply v_not_mem_range
    have scaled_mem : c⁻¹ • x ∈ LinearMap.range H :=
      Submodule.smul_mem _ c⁻¹ hx.2
    have scaled_eq : c⁻¹ • x = v := by
      rw [← hcx]
      simp [hc]
    rwa [scaled_eq] at scaled_mem

/-- If `ker H` and `range H` are disjoint, every generalized zero-eigenvector
is already an ordinary zero-eigenvector. -/
theorem apply_eq_zero_of_pow_apply_eq_zero
    (H : V →ₗ[K] V)
    (ker_range_disjoint : Disjoint (LinearMap.ker H) (LinearMap.range H)) :
    ∀ (n : Nat) (x : V), (H ^ n) x = 0 → H x = 0
  | 0, x, power_zero => by
      have x_zero : x = 0 := by simpa using power_zero
      simp [x_zero]
  | n + 1, x, power_zero => by
      have previous_power_zero : (H ^ n) (H x) = 0 := by
        rw [← Module.End.mul_apply, ← pow_succ]
        exact power_zero
      have H_Hx_zero : H (H x) = 0 :=
        apply_eq_zero_of_pow_apply_eq_zero H ker_range_disjoint n (H x)
          previous_power_zero
      have Hx_mem_bot : H x ∈ (⊥ : Submodule K V) :=
        ker_range_disjoint.le_bot
          ⟨LinearMap.mem_ker.mpr H_Hx_zero, LinearMap.mem_range_self H x⟩
      simpa using Hx_mem_bot

/-- Under the bordered hypotheses, the maximal generalized zero-eigenspace is
exactly the ordinary kernel. -/
theorem maxGenEigenspace_zero_eq_ker_of_bordered_injective
    (H : Module.End K V) (v : V) (phi : V →ₗ[K] K)
    (Hv : H v = 0) (phi_v : phi v ≠ 0)
    (border_injective : Function.Injective (borderedOperator H v phi)) :
    H.maxGenEigenspace 0 = LinearMap.ker H := by
  have ker_eq_span :=
    ker_eq_span_of_bordered_injective H v phi Hv phi_v border_injective
  have v_not_mem_range :=
    not_mem_range_of_bordered_injective H v phi Hv phi_v border_injective
  have ker_range_disjoint :=
    disjoint_ker_range_of_ker_eq_span_of_not_mem_range H v ker_eq_span
      v_not_mem_range
  ext x
  constructor
  · intro hx
    rw [Module.End.mem_maxGenEigenspace] at hx
    obtain ⟨n, power_zero⟩ := hx
    simp only [zero_smul, sub_zero] at power_zero
    exact LinearMap.mem_ker.mpr
      (apply_eq_zero_of_pow_apply_eq_zero H ker_range_disjoint n x power_zero)
  · intro hx
    rw [Module.End.mem_maxGenEigenspace]
    refine ⟨1, ?_⟩
    simpa using hx

/--
The full bordered-matrix conclusion used by the certificate proof: the
displayed eigenvalue has algebraic multiplicity one in the characteristic
polynomial.
-/
theorem charpoly_rootMultiplicity_eq_one_of_bordered_injective
    [FiniteDimensional K V]
    (f : Module.End K V) (mu : K) (v : V) (phi : V →ₗ[K] K)
    (fv : f v = mu • v) (phi_v : phi v ≠ 0)
    (border_injective :
      Function.Injective (borderedOperator (f - mu • 1) v phi)) :
    f.charpoly.rootMultiplicity mu = 1 := by
  let H : Module.End K V := f - mu • 1
  have Hv : H v = 0 := by
    simp [H, fv]
  have v_ne_zero : v ≠ 0 := by
    intro v_zero
    apply phi_v
    simp [v_zero]
  have ker_eq_span :=
    ker_eq_span_of_bordered_injective H v phi Hv phi_v border_injective
  have max_eq_ker_H : f.maxGenEigenspace mu = LinearMap.ker H := by
    rw [f.maxGenEigenspace_eq_maxGenEigenspace_zero]
    exact maxGenEigenspace_zero_eq_ker_of_bordered_injective
      H v phi Hv phi_v border_injective
  calc
    f.charpoly.rootMultiplicity mu =
        finrank K (f.maxGenEigenspace mu) :=
      (LinearMap.finrank_maxGenEigenspace_eq f mu).symm
    _ = finrank K (LinearMap.ker H) := by rw [max_eq_ker_H]
    _ = finrank K (Submodule.span K {v}) := by rw [ker_eq_span]
    _ = 1 := finrank_span_singleton v_ne_zero

end BorderLemma

end KnuthFasc8aEx210
