#define main generator_main_hidden
#include "transfer_generator.cpp"
#undef main
#include <iomanip>
static Graph loadg(const std::string&fn){std::ifstream f(fn,std::ios::binary);Graph g;uint64_t n,e;f.read((char*)&n,8);f.read((char*)&e,8);g.states.resize(n);g.rowptr.resize(n+1);g.col.resize(e);g.wt.resize(e);f.read((char*)g.states.data(),8*n);f.read((char*)g.rowptr.data(),8*(n+1));f.read((char*)g.col.data(),4*e);f.read((char*)g.wt.data(),2*e);g.idx.reserve(2*n);for(uint32_t i=0;i<n;i++)g.idx.emplace(g.states[i],i);return g;}
using U128=unsigned __int128;
static std::string s128(U128 x){if(!x)return"0";std::string s;while(x){s.push_back('0'+x%10);x/=10;}std::reverse(s.begin(),s.end());return s;}
static void stepdiag(const Graph&g,const std::vector<U128>&x,std::vector<U128>&y){for(uint32_t i=0;i<g.states.size();i++)if(x[i])for(uint64_t k=g.rowptr[i];k<g.rowptr[i+1];k++)y[g.col[k]]+=x[i]*g.wt[k];}
struct Cross{std::vector<uint64_t>rp;std::vector<uint32_t>ci;std::vector<uint16_t>w;};
static void addcross(const Cross&c,const std::vector<U128>&x,std::vector<U128>&y){for(uint32_t i=0;i<x.size();i++)if(x[i])for(uint64_t k=c.rp[i];k<c.rp[i+1];k++)y[c.ci[k]]+=x[i]*c.w[k];}
int main(int ac,char**av){std::string d=ac>1?av[1]:"data";Graph T=loadg(d+"/T5.bin"),U=loadg(d+"/U5.bin"),W=loadg(d+"/W5.bin");auto build=[&](const Graph&src,const Graph&dst,int kind){Cross c;c.rp.push_back(0);for(uint32_t i=0;i<src.states.size();i++){Out out;if(kind==1)out=stable_open(closed_to_open(src.states[i]),1,true);else if(kind==2){out=stable_open(closed_to_open(src.states[i]),2,true);for(auto&e:out)e.first=drop_inf(e.first);}else{out=stable_open(src.states[i],2,true);for(auto&e:out)e.first=drop_inf(e.first);}for(auto&e:out){auto it=dst.idx.find(e.first);if(it==dst.idx.end())throw std::runtime_error("cross target missing");c.ci.push_back(it->second);c.w.push_back(e.second);}c.rp.push_back(c.ci.size());}return c;};
 Cross T1=build(T,U,1),T2=build(T,W,2),U2=build(U,W,3);std::vector<U128>x0(T.states.size()),x1(U.states.size()),x2(W.states.size());x0[T.idx.at(0)]=1;std::vector<uint32_t>fT(T.states.size()),fU(U.states.size()),fW(W.states.size());for(uint32_t i=0;i<T.states.size();i++){fT[i]=finish_closed(T.states[i]);}std::vector<uint32_t>fTopen(T.states.size());for(uint32_t i=0;i<T.states.size();i++)fTopen[i]=finish_open(closed_to_open(T.states[i]));for(uint32_t i=0;i<U.states.size();i++)fU[i]=finish_open(U.states[i]);for(uint32_t i=0;i<W.states.size();i++)fW[i]=finish_closed(W.states[i]);
 for(int k=0;k<=10;k++){U128 closed=0,open=0;for(uint32_t i=0;i<T.states.size();i++){closed+=x0[i]*fT[i];open+=x0[i]*fTopen[i];}for(uint32_t i=0;i<U.states.size();i++)open+=x1[i]*fU[i];for(uint32_t i=0;i<W.states.size();i++)open+=x2[i]*fW[i];std::cout<<"n="<<k+2<<" closed="<<s128(closed)<<" open="<<s128(open)<<"\n";std::vector<U128>y0(T.states.size()),y1(U.states.size()),y2(W.states.size());stepdiag(T,x0,y0);stepdiag(U,x1,y1);stepdiag(W,x2,y2);addcross(T1,x0,y1);addcross(T2,x0,y2);addcross(U2,x1,y2);x0.swap(y0);x1.swap(y1);x2.swap(y2);}return 0;}
